"correct" but "incorrect"
there is a problem with the recurse function so it will need more work.
got the bottom up method working but it is getting different results
from the expected output. how the method currently works it is getting
different denomination values from the expected but it has the same
total amount of denominations used?

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,10 +1,17 @@
 #!/bin/bash
 
-if [[ $3 = "rust" ]]; then
+if [[ $3 == "rust" ]]; then
     cargo build -p $1 --release
 
     if (( $? != 0 )); then
         echo "failed to create main for $1"
+        exit 0
+    fi
+elif [[ $3 == "rust-debug" ]]; then
+    cargo build -p $1
+
+    if (( $? != 0 )); then
+        echo "failed to create debug main for $1"
         exit 0
     fi
 else
@@ -17,13 +24,17 @@ else
 fi
 
 run_cpp() {
+    no_diff=false
     in_file="./${1}/tests/${2}.in"
     out_file="./${1}/tests/${2}.out"
     output="./${1}/main.output"
     main="./${1}/main"
 
-    if [[ $3 = "rust" ]]; then
+    if [[ $3 == "rust" ]]; then
         main="./target/release/${1}"
+    elif [[ $3 == "rust-debug" ]]; then
+        main="./target/debug/${1}"
+        no_diff=true
     fi
 
     if [[ ! -f $in_file ]]; then
@@ -32,18 +43,31 @@ run_cpp() {
     fi
 
     if [[ -f $out_file ]]; then
-        echo "checking ${2}"
+        if [[ $no_diff == true ]]; then
+            cat $in_file | $main
 
-        cat $in_file | $main > $output
+            if (( $? != 0 )); then
+                echo "non 0 return from main"
 
-        if (( $? != 0 )); then
-            echo "non 0 return from main"
-            cat $output
+                return 1
+            fi
 
-            return 1
+            echo "----- expected output -----"
+            cat $out_file
+        else
+            echo "checking ${2}"
+
+            cat $in_file | $main > $output
+
+            if (( $? != 0 )); then
+                echo "non 0 return from main"
+                cat $output
+
+                return 1
+            fi
+
+            diff $out_file $output
         fi
-
-        diff $out_file $output
     else
         echo "running ${1}"
 
@@ -53,7 +77,7 @@ run_cpp() {
     return 0
 }
 
-if [[ $2 = "all" ]]; then
+if [[ $2 == "all" ]]; then
     for index in $(seq 1 100); do
         padded=$(printf %3s $index | tr ' ' 0)
         name="test_${padded}"
